dependencies:
- name:  mysql
  version: 1.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
- name:  rabbitmq
  version: 6.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
- name:  rabbitmq-ha
  version: 1.34.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq-ha.enabled
- name:  kafka
  version: 0.13.11
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: kafka.enabled
- name: prometheus
  version: 9.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: features.monitoring.enabled
- name: grafana
  version: 4.0.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: features.monitoring.enabled
